"""add form_starts table

Revision ID: 79dd03e54141
Revises: 3e9c86a922b8
Create Date: 2026-07-10 16:58:30.951359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dd03e54141'
down_revision = '3e9c86a922b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_starts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('race_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('margin', sa.String(length=32), nullable=True),
    sa.Column('distance', sa.String(length=32), nullable=True),
    sa.Column('track_condition', sa.String(length=32), nullable=True),
    sa.Column('starting_price', sa.Numeric(), nullable=True),
    sa.Column('venue', sa.String(length=128), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('is_jumpout', sa.Boolean(), nullable=False),
    sa.Column('external_race_id', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_starts')
    # ### end Alembic commands ###
