"""add race_number to events

Revision ID: 95a3292ae9db
Revises: 79dd03e54141
Create Date: 2026-07-10 17:20:17.474551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a3292ae9db'
down_revision = '79dd03e54141'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('race_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'race_number')
    # ### end Alembic commands ###
