"""add pid to refresh_runs

Revision ID: e68f1053f552
Revises: fdbfc5d40ff8
Create Date: 2026-07-12 01:43:45.845513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68f1053f552'
down_revision = 'fdbfc5d40ff8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_runs', sa.Column('pid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_runs', 'pid')
    # ### end Alembic commands ###
